### PR TITLE
Workflow refresh

### PR DESCRIPTION
**Pull request by akubaryk**
This PR addresses three parts of #22: the extension of med.rc, the writing of SWIO output at the last model timestep, and a for-now default configuration of one-hour output for WAM-IPE and standaloneWAM SWIO output for each model component. It does not link SWIO output into the RUNDIR because of an apparent PNetCDF bug (or inconsistency with the standard NetCDF Fortran library) -- this has been confirmed with PNetCDF 1.10.0 and 1.11.2 on Hera, and 1.8.1 on WCOSS Phase 3. We have the options of cp'ing those files out manually, planning future work to pass a path in the SWIO resource file (which will require further changes to SWIO and COMIO to support), or diagnosing the issue in the PNetCDF library.

### CODE REVIEW

**Comment by ZhuxiaoLi66** [comment]
I redownloaded the workflow_refresh branch and did an 1hr run, it looks that the  gsm.20130316_010000.nc and  ipe.20130316_010000.nc both have good file size at stmp4. 

As for another way, pulled the updates to my original local workflow_refresh branch and 
did 'git submodule update --recursive' under GSMWAM-IPE directory, seems still can't get the right files. what else I missed to do?

**Comment by rmontuoro** [comment]
Commit 7e47447 allows to build the SWPC mediator intermediate 3D mesh using vertical levels imported from IPE if they are not provided in the mediator's configuration file.

**Comment by rmontuoro** [comment]
The [workflow_refresh](https://github.com/NOAA-SWPC/GSMWAM-IPE/tree/workflow_refresh) branch was updated to include the following additional requirements:
- export total electron density (9 species) from IPE
- export thermosphere mass density and mean molecular mass from WAM
- add above fields to SWIO output

**Comment by ZhuxiaoLi66** [comment]
num_density_io_refresh_2013031601
num_density_netcdf_output_20150317

**Comment by ZhuxiaoLi66** [comment]
mms_io_refresh_2013031601

**Comment by rmontuoro** [comment]
Updated thermosphere mean molecular mass units to amu (commit abd5678b).

**Comment by twfang** [comment]
Everything works as expected. I did runs on both Hera and WCOSS and checked the Ne and drifts.

**Comment by ZhuxiaoLi66** [comment]
I did a 24hr workflow_refresh run, checked the number density and mean mass in the SWIO output and the original WAM output, the results are very close.

**Pull request merged**
